Add Makefile, .gitignore, and initial implementation of folder parsing with threading
ReDevCafe/Prismarine pull request #1
Opened 2024-12-31 11:51 UTC by AmeliaCute

2025-02-12 03:03 UTC, EltyDev requested changes
CMAKE NON ?

2025-02-12 03:37 UTC, AmeliaCute commented
Rololo

2025-03-24 17:21 UTC, AmeliaCute commented
> CMAKE NON ?

Okay ntm je le fais 🔫

2025-03-25 03:50 UTC, EltyDev commented on .vscode/launch.json
Les fichiers dans .vscode, c'est pas utile de les push

2025-03-25 03:53 UTC, EltyDev commented on CMakeLists.txt
> +    COMMAND valgrind --leak-check=full --track-origins=yes ${CMAKE_BINARY_DIR}/prismarine ${VALGRIND_EXEC_PARAMETER}
Faut faire gaffe valgrind existe nativement uniquement sur linux

2025-03-25 03:53 UTC, EltyDev commented on CMakeLists.txt
> +set(VALGRIND_EXEC_PARAMETER "/mnt/d/Repos/Momento/src/main/java/")
Absolute path 🤢

2025-03-25 03:56 UTC, EltyDev commented on source/Mapper/Mapper.c
> +PrismPackage* ParseFolder(const char* folderPath, int isRoot)
En vrai tu peux utiliser stdbool.h pour utiliser les booléens, question de visibilité

2025-03-25 03:57 UTC, EltyDev commented on source/Mapper/Mapper.c
> +    package->numChildrenPrisms = 0;
Pas besoins d'initialiser les membres de ta structure à 0, calloc le fait déjà

2025-03-25 04:02 UTC, EltyDev commented on source/Mapper/Mapper.c
> +    pthread_t* threads = calloc(4096, sizeof(pthread_t));
Beaucoup trop de thread, essaye de calculer le nombre de threads dispo

2025-03-25 04:08 UTC, EltyDev commented on source/Mapper/Mapper.c
> +        package->childrensFolders = (PrismPackage*) realloc(
Pourquoi réallouer la mémoire ici pour la exacte même taille ?

2025-03-25 04:37 UTC, EltyDev requested changes
J'ai fait un test de thread et tout à l'air d'aller, sinon corrige ce que j'ai dis et ça sera good

2025-03-25 05:36 UTC, EltyDev commented on source/Mapper/Mapper.c
> +    free_prism_package(package);
Ne surtout pas l'appeler ici sinon l'objet n'est plus utilisable plus tard

2025-03-25 05:37 UTC, EltyDev commented on source/Mapper/Mapper.c
> +    free_prism_package(package);
Et donc si on enlève ce free ici, il faut refaire la fonction free_prism_package qui devient donc obseléte

2025-03-25 05:45 UTC, EltyDev commented on source/Mapper/Mapper.c
> +    pthread_t* threads = calloc(4096, sizeof(pthread_t));
D'ailleurs j'aime pas trop la forme récursif car le programme peut vite overheat, des threads qui crée encore des threads (4060n)² threads bon ...

2025-03-25 17:35 UTC, AmeliaCute commented on source/Mapper/Mapper.c
> +PrismPackage* ParseFolder(const char* folderPath, int isRoot)
`int isRoot` ?

2025-03-25 17:39 UTC, AmeliaCute commented on source/Mapper/Mapper.c
> +    free_prism_package(package);
C'est vrai que cette ligne, je sais meme pas ce qu'elle fout la

2025-03-26 16:59 UTC, EltyDev commented on source/Prismarine.h
> +extern int MAX_THREADS;
NON PAS EXTERNE

2025-03-26 17:01 UTC, EltyDev requested changes
Juste enlève le fait que le champs soit externe car c'est defacto une variable moins rapide

2025-03-29 19:33 UTC, EltyDev commented on source/Prismarine.h
> +int MAX_THREADS __attribute__((common));
Weird flex but ok

2025-03-29 19:34 UTC, EltyDev approved these changes
Ok

2025-03-29 19:35 UTC, merged